TESTNET = False # False for mainnet

SUPPORTED_TOKENS = {
    'ETH': 'NONE',
    'USDT': 'ADD_CONTRACT_ADDRESS',
    'USDC': 'ADD_CONTRACT_ADDRESS',
    'MATIC': 'ADD_CONTRACT_ADDRESS',
    'AVAX': 'ADD_CONTRACT_ADDRESS',
    'LINK': 'ADD_CONTRACT_ADDRESS',
    'wBTC': 'ADD_CONTRACT_ADDRESS',
    'wETH': 'ADD_CONTRACT_ADDRESS',
    'AAVE': 'ADD_CONTRACT_ADDRESS'
}

MAINNET_RPC = 'https://mainnet.infura.io/v3/969ac2404bb14bb8a43259afa7935e0f'
TESTNET_RPC = 'https://goerli.infura.io/v3/969ac2404bb14bb8a43259afa7935e0f'

DEFAULT_GAS_LIMIT = 21000
TOKEN_GAS_LIMIT = 60000

ETHEREUM_CHAIN_ID = 1
GOERLI_CHAIN_ID = 5

WALLET_FILENAME = 'wallet.txt'
